# SHOPPONG CART PROGRAM


# foods = []
# prices = []
# total = 0


# while True:
#     food = input("Enter a food to buy (q to quit): ")
#     if food.lower() == "q":
#         break
#     else:
#         price = float(input(f"Enter the  price of a  food  {food}: $"))
#         foods.append(food)
#         prices.append(price)

# print("---------YOUR CART---------")
# for food,price in zip(foods,prices):
#     print(f"{food} - ${price:.2f}")

# total = sum(prices)
# print(f"\nYour total price is: ${total:.2f}")


# 2d list
# fruits = ["apple", "banana", "mango"]
# vegetables = ["carrot", "spinach", "potato"]
# meats = ["chicken", "beef", "fish"]

# groceries = [fruits,vegetables,meats]
# labels = ["fruits","vegetables","meats"]
# # for fruit,vegetable,meat in zip(fruits,vegetables,meats):
# #     print(f"{fruit:5},{vegetable:5},{meat:5}")


# for category in range(len(groceries)):
#         print(f"\n{labels[category]}:")
#         for item in groceries[category]:
#                 print(f"- {item}")



# num_pad = ((1,2,3),(4,5,6),(7,8,9),("*",0,"#"))


# for row in num_pad:
#     for num in row:
#         print(num,end=" ")
#     print()



